version: '3.8'

services:
  web:
    build: .
    command: uvicorn app:asgi_app --host 0.0.0.0 --port 8000
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1